language: java
sudo: false
install: true
addons:
  sonarqube:
    token:
      secure: "em1oohvG43FXUxhgLybCwFk8Ecqc8kJkT02S/HvvNg97d/4VdHGGNYZzTItshiVL4cB9OH32rou/yRiSpTY3YOGyaOwSx+wlJ8ZE8jWhBiLakrW1U+QvCYhq6392tCcKZyHgBO2IAhN7c204uDVk2m5ID8DoCMUq1VQLsonx/Y6oym8UWvyi97XP6scCyRUGec/9MQY1YpPWU2ZWQZMD1ouOt3MI6zdikX6yO+6PUn3ApPMaE1hE61MIq/DzzpvX6Cvu4sXdn/qm2TD47rIUK0MB4eHS6hIzwxsAH/uX6X5q5jSaNdmJdJVAoEQ2n7Kr+BoJ4oEzZ8EN49rSaUtmbMIETTL/Rrd2UjWrm/rfmBlD1zkapBOSVl9T/dtbpxSvB16HwDQWmOA+aQw4Ioe0WwGXOZRfOClldtDo8EIx0u5pIDa75FySCDiQR0ZaOxrTJ23k13tqRO30EYUKuZY3OKInkI6c5dakxCqr6gCbCYTPQMY1piJNSXNJqh77QVIhs/mNfeaVBv3XpsOAQylhCdJkUgH4O1cjQu7/Dkb045GCrZzEn0wd4+XU8+I6enpeYcomd1EazZX5trjpDJSN2C8Oc61idTDlO4TJ3u1NcZVInQnYO4vIVHjq6dNoc6E+DS8xFhx662xS4kxPAc/CG0iUei3suc4Oc8JU7Pwn08U="
jdk:
- oraclejdk8
script:
- mvn clean package
cache:
  directories:
  - "$HOME/.m2/repository"
branches:
  except:
  - gh-pages
